### ISSUE TITLE
Adapt packaging scripts to allow installing two different versions in parallel

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dmqnode#11]
This would be needed, for example, when we have multiple nodes running on a server and want to test a different version running on one of them.

**Comment by david-eckardt-sociomantic** [comment]
See #17.

**Comment by david-eckardt-sociomantic** [comment]
Fixed in https://github.com/sociomantic-tsunami/dmqnode/commit/90a64833e510863c9da0709408a250eaeb15df00.
